### ISSUE TITLE
`Alternate channel` view raises invalid URL

### ISSUE THREAD

**Issue by allen-tran** [Trident-Development/linkedin-job-post-discord-bot#6]
Apologies but I missed this bug in my review for #4. There seems to be an issue with the API not returning anything on the alternate channel view.

See example:
<img width="1176" alt=" 2022-08-06 at 2 24 43 PM" src="https://user-images.githubusercontent.com/63386979/183263427-e72e50e7-b7f5-46cf-b61c-e023e11f7d3c.png">

<img width="325" alt=" 2022-08-06 at 2 26 32 PM" src="https://user-images.githubusercontent.com/63386979/183263459-e2da72a6-cbdf-4b48-bfb4-ec6bad1eebe4.png">

We should extract the job id out of this link and then carry out the execution.

**Comment by truongluan303** [comment]
Theoretically this should be fix since we are only grabbing the string before the `?`.

**Comment by truongluan303** [comment]
[This PR](https://github.com/Trident-Development/linkedin-job-post-discord-bot/pull/4) fixed it already. Closing this issue!
